package Recursion;

import java.util.ArrayList;
import java.util.List;

public class FindSubsequence {
    // A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
    public static void main(String[] args) {
        List<String> subsequences = findSubSequence("ABC");
        for (String str : subsequences) {
            System.out.println(str);
        }
    }

    private static List<String> findSubSequence(String abc) {
        if (abc.length() == 0) {
            List<String> subSequences = new ArrayList<>();
            subSequences.add("");
            return subSequences;
        }
        char firstCharacter = abc.charAt(0);

        List<String> subsequences = findSubSequence(abc.substring(1));
        List<String> subSequencesFinal = new ArrayList<>();
        for (String subsequence : subsequences) {
            subSequencesFinal.add(firstCharacter + subsequence);
            subSequencesFinal.add("" + subsequence);
        }
        return subSequencesFinal;

    }
}
